/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAccountRouteImport } from './routes/admin/account'
import { Route as AdminCoupleRouteImport } from './routes/admin/couple'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as AdminFamilyRouteImport } from './routes/admin/family'
import { Route as AdminFooterRouteImport } from './routes/admin/footer'
import { Route as AdminGalleryRouteImport } from './routes/admin/gallery'
import { Route as AdminHeroRouteImport } from './routes/admin/hero'
import { Route as AdminHeroVideoRouteImport } from './routes/admin/hero-video'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminMusicRouteImport } from './routes/admin/music'
import { Route as AdminNavigationRouteImport } from './routes/admin/navigation'
import { Route as AdminQuotesRouteImport } from './routes/admin/quotes'
import { Route as AdminReelsRouteImport } from './routes/admin/reels'
import { Route as AdminSectionsRouteImport } from './routes/admin/sections'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSpecialBlessingsRouteImport } from './routes/admin/special-blessings'
import { Route as AdminWeddingReelsRouteImport } from './routes/admin/wedding-reels'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoupleRoute = AdminCoupleRouteImport.update({
  id: '/couple',
  path: '/couple',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFamilyRoute = AdminFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFooterRoute = AdminFooterRouteImport.update({
  id: '/footer',
  path: '/footer',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeroVideoRoute = AdminHeroVideoRouteImport.update({
  id: '/hero-video',
  path: '/hero-video',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMusicRoute = AdminMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNavigationRoute = AdminNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotesRoute = AdminQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReelsRoute = AdminReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSectionsRoute = AdminSectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSpecialBlessingsRoute = AdminSpecialBlessingsRouteImport.update({
  id: '/special-blessings',
  path: '/special-blessings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWeddingReelsRoute = AdminWeddingReelsRouteImport.update({
  id: '/wedding-reels',
  path: '/wedding-reels',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/account': typeof AdminAccountRoute
  '/admin/couple': typeof AdminCoupleRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/family': typeof AdminFamilyRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/hero-video': typeof AdminHeroVideoRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/music': typeof AdminMusicRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/reels': typeof AdminReelsRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/special-blessings': typeof AdminSpecialBlessingsRoute
  '/admin/wedding-reels': typeof AdminWeddingReelsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/couple': typeof AdminCoupleRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/family': typeof AdminFamilyRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/hero-video': typeof AdminHeroVideoRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/music': typeof AdminMusicRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/reels': typeof AdminReelsRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/special-blessings': typeof AdminSpecialBlessingsRoute
  '/admin/wedding-reels': typeof AdminWeddingReelsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/account': typeof AdminAccountRoute
  '/admin/couple': typeof AdminCoupleRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/family': typeof AdminFamilyRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/hero-video': typeof AdminHeroVideoRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/music': typeof AdminMusicRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/reels': typeof AdminReelsRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/special-blessings': typeof AdminSpecialBlessingsRoute
  '/admin/wedding-reels': typeof AdminWeddingReelsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/account'
    | '/admin/couple'
    | '/admin/events'
    | '/admin/family'
    | '/admin/footer'
    | '/admin/gallery'
    | '/admin/hero'
    | '/admin/hero-video'
    | '/admin/login'
    | '/admin/media'
    | '/admin/music'
    | '/admin/navigation'
    | '/admin/quotes'
    | '/admin/reels'
    | '/admin/sections'
    | '/admin/settings'
    | '/admin/special-blessings'
    | '/admin/wedding-reels'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/account'
    | '/admin/couple'
    | '/admin/events'
    | '/admin/family'
    | '/admin/footer'
    | '/admin/gallery'
    | '/admin/hero'
    | '/admin/hero-video'
    | '/admin/login'
    | '/admin/media'
    | '/admin/music'
    | '/admin/navigation'
    | '/admin/quotes'
    | '/admin/reels'
    | '/admin/sections'
    | '/admin/settings'
    | '/admin/special-blessings'
    | '/admin/wedding-reels'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/account'
    | '/admin/couple'
    | '/admin/events'
    | '/admin/family'
    | '/admin/footer'
    | '/admin/gallery'
    | '/admin/hero'
    | '/admin/hero-video'
    | '/admin/login'
    | '/admin/media'
    | '/admin/music'
    | '/admin/navigation'
    | '/admin/quotes'
    | '/admin/reels'
    | '/admin/sections'
    | '/admin/settings'
    | '/admin/special-blessings'
    | '/admin/wedding-reels'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/couple': {
      id: '/admin/couple'
      path: '/couple'
      fullPath: '/admin/couple'
      preLoaderRoute: typeof AdminCoupleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/family': {
      id: '/admin/family'
      path: '/family'
      fullPath: '/admin/family'
      preLoaderRoute: typeof AdminFamilyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/footer': {
      id: '/admin/footer'
      path: '/footer'
      fullPath: '/admin/footer'
      preLoaderRoute: typeof AdminFooterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hero-video': {
      id: '/admin/hero-video'
      path: '/hero-video'
      fullPath: '/admin/hero-video'
      preLoaderRoute: typeof AdminHeroVideoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/music': {
      id: '/admin/music'
      path: '/music'
      fullPath: '/admin/music'
      preLoaderRoute: typeof AdminMusicRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/navigation': {
      id: '/admin/navigation'
      path: '/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AdminNavigationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotes': {
      id: '/admin/quotes'
      path: '/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminQuotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reels': {
      id: '/admin/reels'
      path: '/reels'
      fullPath: '/admin/reels'
      preLoaderRoute: typeof AdminReelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sections': {
      id: '/admin/sections'
      path: '/sections'
      fullPath: '/admin/sections'
      preLoaderRoute: typeof AdminSectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/special-blessings': {
      id: '/admin/special-blessings'
      path: '/special-blessings'
      fullPath: '/admin/special-blessings'
      preLoaderRoute: typeof AdminSpecialBlessingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wedding-reels': {
      id: '/admin/wedding-reels'
      path: '/wedding-reels'
      fullPath: '/admin/wedding-reels'
      preLoaderRoute: typeof AdminWeddingReelsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAccountRoute: typeof AdminAccountRoute
  AdminCoupleRoute: typeof AdminCoupleRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminFamilyRoute: typeof AdminFamilyRoute
  AdminFooterRoute: typeof AdminFooterRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminHeroRoute: typeof AdminHeroRoute
  AdminHeroVideoRoute: typeof AdminHeroVideoRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminMusicRoute: typeof AdminMusicRoute
  AdminNavigationRoute: typeof AdminNavigationRoute
  AdminQuotesRoute: typeof AdminQuotesRoute
  AdminReelsRoute: typeof AdminReelsRoute
  AdminSectionsRoute: typeof AdminSectionsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSpecialBlessingsRoute: typeof AdminSpecialBlessingsRoute
  AdminWeddingReelsRoute: typeof AdminWeddingReelsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountRoute: AdminAccountRoute,
  AdminCoupleRoute: AdminCoupleRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminFamilyRoute: AdminFamilyRoute,
  AdminFooterRoute: AdminFooterRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminHeroRoute: AdminHeroRoute,
  AdminHeroVideoRoute: AdminHeroVideoRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminMusicRoute: AdminMusicRoute,
  AdminNavigationRoute: AdminNavigationRoute,
  AdminQuotesRoute: AdminQuotesRoute,
  AdminReelsRoute: AdminReelsRoute,
  AdminSectionsRoute: AdminSectionsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSpecialBlessingsRoute: AdminSpecialBlessingsRoute,
  AdminWeddingReelsRoute: AdminWeddingReelsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
